# SPDX-License-Identifier: GPL-2.0
# FPC1542 (ported from 4.14 everpal tree; TEEI paths adjusted to drivers/tee/)
obj-$(CONFIG_INPUT_FINGERPRINT_FPC1542) += mtk_spi.o
ccflags-$(CONFIG_INPUT_FINGERPRINT_FPC1542) += -I$(srctree)/drivers/tee/teei/400/tz_driver/include/
ccflags-$(CONFIG_INPUT_FINGERPRINT_FPC1542) += -I$(srctree)/drivers/tee/teei/400/common/include/
