# SPDX-License-Identifier: GPL-2.0
# everpal: ported from 4.14 tree, 5.10 isp6s subdrv pattern
#include $(srctree)/drivers/misc/mediatek/Makefile.custom

imgsensor_isp6s-objs += \
	$(subdrv-rpath)/imx355ofilmmipiraw_Sensor.o \
	$(subdrv-rpath)/imx355ofilm_eeprom.o
